### ISSUE TITLE
Tweaks suggested for section 'Variation Types and Choices'

### ISSUE THREAD

**Issue by DDvO** [anima-wg/brski-discovery#2]
replace

enroll: : A variation in the URI endpoints used for enrollment of the pledge with keying material (trust anchors and certificate (chain)). This document introduces the choices "est" as introduced by {{BRSKI}} (to indicate the {{EST}} protocol) and "cmp" to indicate the lightweight CMP profile ({{lwCMP}}) introduced by {{BRSKI-AE}}. It also reserved the choice "scep" to indicate {{SCEP}}. This is only a reservation, because no specification for the use of {{SCEP}} with BRSKI exist.

by

enroll: : A variation in the URI endpoints used for enrollment of the pledge with keying material (trust anchors and certificate (chain)). This document introduces the choices
* "est" as introduced by {{BRSKI}} to indicate the {{EST}} protocol, which is default
* "cmp" to indicate the {{CMP}} protocol according to the Lightweight CMP profile ({{lwCMP}}). The respective adaptations to BRSKI have been introduced by {{BRSKI-AE}}.
* "scep" to indicate {{SCEP}}. This is only a reservation, because no specification for the use of {{SCEP}} with BRSKI exists.

**Comment by DDvO** [comment]
@toerless hope you saw this little suggestion?
What do you think?

**Comment by toerless** [comment]
Included in next commit. Thanks.
